import 'package:hulu_coffee_pos/shared/models/product_models.dart';

// Updated to use String categories (matching category.name keys)
final List<Product> dummyProducts = [
  const Product(
    id: 'p1',
    name: 'Iced Latte',
    description: 'ESPRESSO • MILK',
    price: 65000,
    imageUrl: '',
    category: 'coffee',
  ),
  const Product(
    id: 'p2',
    name: 'Americano',
    description: 'ESPRESSO • WATER',
    price: 50000,
    imageUrl: '',
    category: 'coffee',
  ),
  const Product(
    id: 'p3',
    name: 'Cappuccino',
    description: 'ESPRESSO • FOAM',
    price: 68000,
    imageUrl: '',
    category: 'coffee',
  ),
  const Product(
    id: 'p4',
    name: 'Mocha',
    description: 'ESPRESSO • CHOCOLATE',
    price: 75000,
    imageUrl: '',
    category: 'coffee',
  ),
  const Product(
    id: 'p5',
    name: 'Cold Brew',
    description: 'STEEPED 24H',
    price: 55000,
    imageUrl: '',
    isAvailable: false,
    category: 'coffee',
  ),
  const Product(
    id: 'p6',
    name: 'Matcha Latte',
    description: 'MATCHA • MILK',
    price: 60000,
    imageUrl: '',
    category: 'nonCoffee',
  ),
  const Product(
    id: 'p7',
    name: 'Peach Tea',
    description: 'BLACK TEA • PEACH',
    price: 45000,
    imageUrl: '',
    category: 'tea',
  ),
  const Product(
    id: 'p8',
    name: 'Butter Croissant',
    description: 'PASTRY',
    price: 35000,
    imageUrl: '',
    category: 'snacks',
  ),
];
