import 'package:hulu_coffee_pos/shared/models/product_models.dart';

final List<Product> dummyProducts = [
  const Product(
    id: 'p1',
    name: 'Iced Latte',
    description: 'ESPRESSO • MILK',
    price: 65000,
    imageUrl: 'assets/images/iced_latte.png',
    category: ProductCategory.coffee,
  ),
  const Product(
    id: 'p2',
    name: 'Americano',
    description: 'ESPRESSO • WATER',
    price: 50000,
    imageUrl: 'assets/images/americano.png',
    category: ProductCategory.coffee,
  ),
  const Product(
    id: 'p3',
    name: 'Cappuccino',
    description: 'ESPRESSO • FOAM',
    price: 68000,
    imageUrl: 'assets/images/cappuccino.png',
    category: ProductCategory.coffee,
  ),
  const Product(
    id: 'p4',
    name: 'Mocha',
    description: 'ESPRESSO • CHOCOLATE',
    price: 75000,
    imageUrl: 'assets/images/mocha.png',
    category: ProductCategory.coffee,
  ),
  const Product(
    id: 'p5',
    name: 'Cold Brew',
    description: 'STEEPED 24H',
    price: 55000,
    imageUrl: 'assets/images/cold_brew.png',
    isAvailable: false,
    category: ProductCategory.coffee,
  ),
  const Product(
    id: 'p6',
    name: 'Matcha Latte',
    description: 'MATCHA • MILK',
    price: 60000,
    imageUrl: 'assets/images/matcha.png',
    category: ProductCategory.nonCoffee,
  ),
  const Product(
    id: 'p7',
    name: 'Peach Tea',
    description: 'BLACK TEA • PEACH',
    price: 45000,
    imageUrl: 'assets/images/peach_tea.png',
    category: ProductCategory.tea,
  ),
  const Product(
    id: 'p8',
    name: 'Butter Croissant',
    description: 'PASTRY',
    price: 35000,
    imageUrl: 'assets/images/croissant.png',
    category: ProductCategory.snacks,
  ),
];
